# """Subclass of WizardSQLitePageView, which is generated by wxFormBuilder."""
#
import wx
#
# from yodatools.dataloader.view.WizardSQLitePageView import WizardSQLitePageView
#
# class WizardSQLitePageController(WizardSQLitePageView):
#     def __init__(self, parent, title=''):
#         super(WizardSQLitePageView, self).__init__(parent)
#         self.title = title
#
#     def on_browse_button(self, event):
#         dialog = wx.FileDialog(
#             self,
#             message='Add file',
#             style=wx.FD_CHANGE_DIR
#         )
#
#         if dialog.ShowModal() != wx.ID_OK:
#             return
#
#         #does the file exist?
#         #if yes, then continue
#         #if no, run sql command to populate it, then continue
#
#         self.file_text_ctrl.SetValue(dialog.GetPath())

from yodatools.dataloader.view.WizardDatabasePageView import WizardDatabasePageView


class WizardSQLitePageController(WizardDatabasePageView):
    def __init__(self, parent, title=''):
        super(WizardSQLitePageController, self).__init__(parent)
        self.title = title

        self.panel.choices = {
            'SQLite': 'sqlite'
        }
        self.panel.cbDatabaseType.SetItems(self.panel.choices.keys())
        self.panel.cbDatabaseType.SetStringSelection('SQLite')


        self.panel.txtDBName.Disable()
        self.panel.txtPass.Disable()
        self.panel.txtUser.Disable()
        self.panel.stDBName.Disable()
        self.panel.stPass.Disable()
        self.panel.stUser.Disable()
        self.panel.stServer.SetLabel("SQLite File Path:")



        self.btnBrowse = wx.Button(self.panel, wx.ID_ANY, 'Browse', wx.DefaultPosition, wx.DefaultSize, 0)  # noqa
        self.panel.btnSizer.Add(self.btnBrowse, 1, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_CENTER_HORIZONTAL, 5)  # noqa
        self.panel.Layout()
        # Connect Events.
        self.btnBrowse.Bind(wx.EVT_BUTTON, self.OnBtnBrowse)


    def OnBtnBrowse(self, event):
        dialog = wx.FileDialog(
            self,
            'ODM2 SQLite file',
            wildcard="SQLite File (*.sqlite)|*.sqlite",
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST
        )

        # with wx.FileDialog(self, "Save XYZ file", wildcard="XYZ files (*.xyz)|*.xyz",
        #                    style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT) as fileDialog:

        #the sqlite file must exist and have the tables generated for the code to work.
        if dialog.ShowModal() != wx.ID_OK:
            return

        path = dialog.GetPath()
        dialog.Destroy()
        # open file for reading
        fh = open(path, 'r')
        # if file does not exist, create it
        if (fh is None):
            fh = open(fh, "w")
        self.panel.txtServer.SetValue(path)

